### ISSUE TITLE
Clustering methods

### ISSUE THREAD

**Issue by ghost** [GuillaumeErhard/ImageSetCleaner#3]

**Comment by GuillaumeErhard** [comment]
Hello Hamzeh2,

This project is not that fresh in my head, but I tried to remember what could have led me to those choices.
First something off the shelf, for time constraint. Something that computes fast. And then you want something that works great with non euclidean spaces. Working on bottlenecks values means you will get a spare vector for each image of positives values.

In a lot of cases the signal of the cluster of correct image should be strong enough for the clustering to be effective though. 

There might be more effective way indeed. If you see any please feel free to share.
